<?xml version="1.0" encoding="utf-8"?><Database Name="gtd" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=localgtd;Integrated Security=True" SettingsObjectName="GettingThingsDone.Properties.Settings" SettingsPropertyName="gtdLocalConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Lists" Member="Lists">
    <Type Name="Lists">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Owner" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Lists_Lists_Tasks" Member="Lists_Tasks" ThisKey="Id,Owner" OtherKey="List_id,Owner" Type="Lists_Tasks" />
      <Association Name="Lists_Projects_Lists" Member="Projects_Lists" ThisKey="Id,Owner" OtherKey="List_id,Owner" Type="Projects_Lists" />
      <Association Name="Lists_Tasks_Lists" Member="Tasks_Lists" ThisKey="Id,Owner" OtherKey="List_id,Owner" Type="Tasks_Lists" />
      <Association Name="Users_Lists" Member="Users" ThisKey="Owner" OtherKey="Id" Type="Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Lists_Tasks" Member="Lists_Tasks">
    <Type Name="Lists_Tasks">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="List_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Task_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Owner" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Lists_Lists_Tasks" Member="Lists" ThisKey="List_id,Owner" OtherKey="Id,Owner" Type="Lists" IsForeignKey="true" />
      <Association Name="Tasks_Lists_Tasks" Member="Tasks" ThisKey="Task_id,Owner" OtherKey="Id,Owner" Type="Tasks" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Projects" Member="Projects">
    <Type Name="Projects">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Owner" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Projects_Projects_Lists" Member="Projects_Lists" ThisKey="Id,Owner" OtherKey="Project_id,Owner" Type="Projects_Lists" />
      <Association Name="Projects_Projects_Tasks" Member="Projects_Tasks" ThisKey="Id,Owner" OtherKey="Project_id,Owner" Type="Projects_Tasks" />
      <Association Name="Users_Projects" Member="Users" ThisKey="Owner" OtherKey="Id" Type="Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Projects_Lists" Member="Projects_Lists">
    <Type Name="Projects_Lists">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Project_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="List_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Owner" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Lists_Projects_Lists" Member="Lists" ThisKey="List_id,Owner" OtherKey="Id,Owner" Type="Lists" IsForeignKey="true" />
      <Association Name="Projects_Projects_Lists" Member="Projects" ThisKey="Project_id,Owner" OtherKey="Id,Owner" Type="Projects" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Projects_Tasks" Member="Projects_Tasks">
    <Type Name="Projects_Tasks">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Project_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Task_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Owner" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Projects_Projects_Tasks" Member="Projects" ThisKey="Project_id,Owner" OtherKey="Id,Owner" Type="Projects" IsForeignKey="true" />
      <Association Name="Tasks_Projects_Tasks" Member="Tasks" ThisKey="Task_id,Owner" OtherKey="Id,Owner" Type="Tasks" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tasks" Member="Tasks">
    <Type Name="Tasks">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DueDate" Type="System.DateTimeOffset" DbType="DateTimeOffset" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="Owner" AutoSync="Always" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Done" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Tasks_Lists_Tasks" Member="Lists_Tasks" ThisKey="Id,Owner" OtherKey="Task_id,Owner" Type="Lists_Tasks" />
      <Association Name="Tasks_Projects_Tasks" Member="Projects_Tasks" ThisKey="Id,Owner" OtherKey="Task_id,Owner" Type="Projects_Tasks" />
      <Association Name="Tasks_Tasks_Lists" Member="Tasks_Lists" ThisKey="Id,Owner" OtherKey="Task_id,Owner" Type="Tasks_Lists" />
      <Association Name="Tasks_Tasks_Tasks" Member="Tasks_Tasks" ThisKey="Id,Owner" OtherKey="Predecessor_Id,Predecessor_Owner" Type="Tasks_Tasks" />
      <Association Name="Tasks_Tasks_Tasks1" Member="Tasks_Tasks1" ThisKey="Id,Owner" OtherKey="Successor_Id,Successor_Owner" Type="Tasks_Tasks" />
      <Association Name="Users_Tasks" Member="Users" ThisKey="Owner" OtherKey="Id" Type="Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tasks_Lists" Member="Tasks_Lists">
    <Type Name="Tasks_Lists">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Task_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="List_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Owner" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Lists_Tasks_Lists" Member="Lists" ThisKey="List_id,Owner" OtherKey="Id,Owner" Type="Lists" IsForeignKey="true" />
      <Association Name="Tasks_Tasks_Lists" Member="Tasks" ThisKey="Task_id,Owner" OtherKey="Id,Owner" Type="Tasks" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tasks_Tasks" Member="Tasks_Tasks">
    <Type Name="Tasks_Tasks">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Predecessor_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Successor_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Predecessor_Owner" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Successor_Owner" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Tasks_Tasks_Tasks" Member="Tasks" ThisKey="Predecessor_Id,Predecessor_Owner" OtherKey="Id,Owner" Type="Tasks" IsForeignKey="true" />
      <Association Name="Tasks_Tasks_Tasks1" Member="Tasks1" ThisKey="Successor_Id,Successor_Owner" OtherKey="Id,Owner" Type="Tasks" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="Users">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Mail" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Users_Lists" Member="Lists" ThisKey="Id" OtherKey="Owner" Type="Lists" />
      <Association Name="Users_Projects" Member="Projects" ThisKey="Id" OtherKey="Owner" Type="Projects" />
      <Association Name="Users_Tasks" Member="Tasks" ThisKey="Id" OtherKey="Owner" Type="Tasks" />
    </Type>
  </Table>
</Database>