//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>La liste dynamique se construit avec une liste cible (statique ou dynamique) et un filtre (à définir).</remarks>
public class DynamicList : TaskList
{
	public virtual StaticList target
	{
		get;
		set;
	}

	public virtual IEnumerator<Task> GetEnumerator()
	{
		throw new System.NotImplementedException();
	}

	public virtual T accept(GTDModel::TaskVisitor<T> v)
	{
		throw new System.NotImplementedException();
	}

}

