//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class SingleTask : Task
{
	public virtual T accept(GTDModel::TaskVisitor<T> v)
	{
		throw new System.NotImplementedException();
	}

}

