//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class SingleTask : Task
{

    String Title { get; set; }
    String Description { get; set; }
    Boolean Done { get; set; }
    DateTime DueDate { get; set; }
    DateTime CreationDate { get; }

	public virtual T accept<T>(TaskVisitor<T> v)
	{
		return v.visit(this);
	}

}

