//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class SingleTask : Task
{

    public String Title { get; set; }
    public String Description { get; set; }
    public Boolean Done { get; set; }
    public DateTime DueDate { get; set; }
    private DateTime creationDate;
    public DateTime CreationDate { get { return creationDate; } }

	public virtual T accept<T>(TaskVisitor<T> v)
	{
		return v.visit(this);
	}

}

