//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Linq;

namespace GettingThingsDone.src.data
{
    public sealed class LocalDatabaseProvider : IDatabaseProvider
    {
        public DataClassesDataContext Database
        {
            get { return new DataClassesDataContext(); }
        }
    }
}

