//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Linq;

namespace GettingThingsDone.data
{
    /// <remarks>C'est du Singleton à instantiation différée par paresse, et thread safe.</remarks>
    public sealed class LocalDatabaseProvider
    {
        private Lazy<DataClassesDataContext> db =
            new Lazy<DataClassesDataContext>(() => new DataClassesDataContext());

        private static Lazy<LocalDatabaseProvider> lazy =
        new Lazy<LocalDatabaseProvider>(() => new LocalDatabaseProvider());

        private DataClassesDataContext getDataContext()
        {
            return db.Value;
        }

        public static DataClassesDataContext Instance
        {
            get { return lazy.Value.getDataContext(); }
        }

        private LocalDatabaseProvider() {}

    }
}

