//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GettingThingsDone.data
{
    public interface TaskVisitor<T> 
    {
        T visit(TaskList list);

        T visit(SingleTask task);

        T visit(Project project);
    }
}

