//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GettingThingsDone.data
{
    public interface TaskVisitor
    {
        void visit(TaskList list);

        void visit(SingleTask task);

        void visit(Project project);
    }
}

