//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>La liste dynamique se construit avec une liste cible (statique ou dynamique) et un filtre (à définir).</remarks>
public class DynamicList : TaskList
{
    public string Name { get; set; }

	public virtual StaticList target
	{
		get;
		set;
	}

    private Func<GTDItem, Boolean> filter;

    public DynamicList(StaticList target, Func<GTDItem, Boolean> filter) {
        this.target = target;
        this.filter = filter;
    }

	public virtual IEnumerator<GTDItem> GetEnumerator()
	{
		return target.Where(filter).GetEnumerator();
	}

    System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

	public virtual T accept<T>(TaskVisitor<T> v)
	{
		return v.visit(this);
	}

    public void removeTask(Task t)
    {
        this.target.removeTask(t);
    }
}

