//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>Cette classe décrit le système général de GTD, avec la boite de reception et les listes de l'utilisateur. On ajoutera surement le calendrier ici.</remarks>
public class GTDSystem : TaskList
{
	public virtual TaskList Inbox
	{
		get;
		set;
	}

	public virtual List<TaskList> Lists
	{
		get;
		set;
	}

	public virtual IEnumerator<GTDItem> GetEnumerator()
	{
		return Lists.GetEnumerator();
	}

    System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

	public virtual T accept<T>(TaskVisitor<T> v)
	{
        return v.visit(this);
    }

}

