//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class SingleTask : Task
{

    public String Title { get; set; }
    public String Description { get; set; }
    public Boolean Done { get; set; }
    public DateTimeOffset? DueDate { get; set; }
    private DateTimeOffset creationDate;
    public DateTimeOffset CreationDate { get { return creationDate; } }
    public DateTimeOffset Reminder { get; set; }
    public String Context { get; set; }


    public SingleTask() : this("")
    {
        
    }

    public SingleTask(string title)
        : this("", "")
    {

    }

    public SingleTask(string title, string desc) : this(title, desc, null)
    {

    }

    public SingleTask(string title, string desc, DateTimeOffset? dueDate)
    {
        this.creationDate = DateTimeOffset.Now;
        this.Done = false;
        this.Title = title;
        this.Description = desc;
        this.DueDate = dueDate;
    }

    public override string ToString()
    {
        return "SingleTask : " + Title + "\n" + Description;
    }

	public virtual T accept<T>(TaskVisitor<T> v)
	{
		return v.visit(this);
	}

}

