//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface TaskList : GTDItem, IEnumerable<GTDItem>
{
   String Name { get; set; }
   void AddTask(Task t);
   void AddSubList(TaskList l);

   void removeTask(Task t);
   void removeSubList(TaskList l);
   void removeProject(Task t);
}

